# Generated by Django 3.1 on 2020-08-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_sketches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketches',
            name='image',
            field=models.ImageField(upload_to='img/images_sketches'),
        ),
    ]
